# Generated by Django 5.1.7 on 2025-04-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rocnik',
            field=models.IntegerField(default=2000),
        ),
    ]
